name: Sign and release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  sign:
    uses: HNVW/UniT.Workflows/.github/workflows/sign-and-release.yml@master
    secrets: inherit
